# git resource
resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/mk-gloamglozer/concourse-testing.git
  - name: node_image
    type: registry-image
    source:
      repository: node
      tag: gallium-alpine
jobs:
  - name: hello-world-job
    plan:
      - get: repo
      - get: node_image
      - task: npm-install
        image: node_image
        config:
          platform: linux
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - -cx
              - |
                cd repo
                ls -la
                npm install
