resources:
  - name: busybox
    type: registry-image
    source:
      repository: busybox
jobs:
  - name: test
    plan:
      - get: busybox
      - task: hello
        image: busybox
        config:
          platform: linux
          run:
            path: echo
            args:
              - "hello world"
